FROM node:latest AS compile-image
WORKDIR ui-app
COPY package.json ./
RUN npm install
COPY . ./
RUN npm run ng build --prod

FROM nginx
COPY env-replace.sh ./
#For below line, check https://angular.io/guide/deployment#routed-apps-must-fallback-to-indexhtml
COPY nginx-custom.conf /etc/nginx/conf.d/default.conf
COPY --from=compile-image /ui-app/dist/* /usr/share/nginx/html
CMD ["/bin/sh",  "-c",  "sh env-replace.sh && exec nginx -g 'daemon off;'"]

