FROM node:latest AS compile-image
RUN npm install -g @angular/cli
WORKDIR ui-app
COPY package.json ./
RUN npm install
COPY . ./
RUN ng build --prod

FROM httpd:alpine
COPY env-replace-apache.sh ./
COPY --from=compile-image /ui-app/dist/* /usr/local/apache2/htdocs/
CMD ["/bin/sh",  "-c",  "sh env-replace-apache.sh && exec httpd-foreground"]

