FROM node:latest AS compile-image
WORKDIR ui-app
COPY package.json ./
RUN npm install
COPY . ./
RUN npm run ng build --prod

FROM httpd:alpine
COPY env-replace-apache.sh ./
#TODO adding angular routing htaccess config https://angular.io/guide/deployment#fallback-configuration-examples
COPY --from=compile-image /ui-app/dist/* /usr/local/apache2/htdocs/
CMD ["/bin/sh",  "-c",  "sh env-replace-apache.sh && exec httpd-foreground"]

